# Generated by Django 5.1.7 on 2025-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='caste_or_ews_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='caste_or_ews_certificates/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
