# Generated by Django 5.1.7 on 2025-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_personalinfo_caste_or_ews_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='currentAddress_PinCode',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='permanentAddress_PinCode',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
